version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI:$COMMIT_HASH .
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$COMMIT_HASH
      - echo Writing image definitions file...
      - >
        printf '{"Parameters": {"DockerTag": "%s", "DesiredCount": "%s",
        "Cluster": "%s", "ECRRepo": "%s", "TargetGroupARN": "%s"}}'
        $COMMIT_HASH $DESIRED_COUNT $CLUSTER $ECR_REPO_NAME $TARGET_GROUP_ARN > params.json
      - echo Getting cfn template from s3...
      - aws s3 cp s3://$BUCKET/templates/service.yaml service.yaml
artifacts:
    files:
      - params.json
      - service.yaml